// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/ticket.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "ticket";

/** Request đặt vé */
export interface CreateOrderRequest {
  user_id: number;
  event_id: number;
  /** số lượng vé muốn mua */
  quantity: number;
}

/** Response đặt vé */
export interface CreateOrderResponse {
  success: boolean;
  message: string;
  /** chỉ khi success = true */
  order_id: number;
}

/** Request kiểm tra trạng thái đơn hàng */
export interface GetOrderStatusRequest {
  order_id: number;
}

/** Response trạng thái đơn hàng */
export interface GetOrderStatusResponse {
  order_id: number;
  success: boolean;
  /** PENDING, SUCCESS, FAILED */
  status: string;
}

/** Request kiểm tra stock */
export interface GetStockRequest {
  event_id: number;
}

/** Response stock */
export interface GetStockResponse {
  event_id: number;
  /** Số lượng vé còn lại hiện tại */
  remaining_stock: number;
}

export const TICKET_PACKAGE_NAME = "ticket";

export interface TicketServiceClient {
  /** Đặt vé */

  createOrder(request: CreateOrderRequest, metadata?: Metadata): Observable<CreateOrderResponse>;

  /** Kiểm tra trạng thái đơn hàng */

  getOrderStatus(request: GetOrderStatusRequest, metadata?: Metadata): Observable<GetOrderStatusResponse>;

  /** Lấy số lượng vé còn lại */

  getStock(request: GetStockRequest, metadata?: Metadata): Observable<GetStockResponse>;
}

export interface TicketServiceController {
  /** Đặt vé */

  createOrder(request: CreateOrderRequest, metadata?: Metadata): Observable<CreateOrderResponse>;

  /** Kiểm tra trạng thái đơn hàng */

  getOrderStatus(request: GetOrderStatusRequest, metadata?: Metadata): Observable<GetOrderStatusResponse>;

  /** Lấy số lượng vé còn lại */

  getStock(request: GetStockRequest, metadata?: Metadata): Observable<GetStockResponse>;
}

export function TicketServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "getOrderStatus", "getStock"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("TicketService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("TicketService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const TICKET_SERVICE_NAME = "TicketService";
